### PR TITLE
Item Encryption

### PR DESCRIPTION
**Pull request by linuxwolf**
Includes a first-pass at item key management

### CODE REVIEW

**Comment by devinreams** [comment]
@jimporter when will you be able to review this?

**Comment by jimporter** [comment]
@devinreams I got halfway through it yesterday and will finish it up today. It's a pretty big diff, so I wanted to make sure I'm not missing anything.

**Comment by devinreams** [comment]
>I got halfway through it yesterday and will finish it up today. 

@jimporter Amazing turnaround! ⚡️Thank you very much. 🙇

**Comment by linuxwolf** [comment]
@jimporter Any questions I should answer?

**Pull request merged**
