### PR TITLE
Update Local IndexedDB Schema

### LINKED ISSUE #78: On-device database schema enhancements for sync
In service to sync, the on-device IndexedDB requires additional collections/tables:

* `pending` to track changes to be applied (locally and remotely)
* `markers` to track the last sync point for each collection (`items` and `keystores`)

Further modifications to the existing `keystores` table are necessary:

* remove `uuid` from the indexes
* add `id` to the record (indexed), set to `HASH(group)`
* add `last_modified` to record (but not indexed) to track the server-provided timestamp

Additional changes to the `items` table are necessary:

* add `last_modified` to record (but not indexed) to track the server-provided timestamp

## Related

* #50

### PR DESCRIPTION
**Pull request by linuxwolf**
Resolves #78

Implements the required changes, plus a couple of placeholders.  The remainder is safer to accomplish when the tables start to be used.

### CODE REVIEW

**Comment by m8ttyB** [comment]
Do you need a PI review of this work?

**Comment by linuxwolf** [comment]
@m8ttyB I suspect this will be like PR #86, where extra eyes will be welcome but not sure what independent verification is possible.

**Comment by linuxwolf** [comment]
@mozilla-lockbox/product-integrity should be ready for a once-over.

**Comment by m8ttyB** [comment]
I see @kimberlythegeek r+ this for PI, adding the pi-verified label.

**Comment by kimberlythegeek** [comment]
@m8ttyB ah, yes, sorry

**Pull request merged**
